services:
    db:
        image: postgres
    
        volumes:
            - pgdata:/var/lib/postgresql/data

        expose:
          - 5432

        env_file:
            - "./.env"

        networks:
          - postgres-network

    pgadmin:
        image: dpage/pgadmin4

        depends_on:
            - db

        environment:
            PGADMIN_CONFIG_SERVER_MODE: 'False'

        volumes:
          - pgadmin:/var/lib/pgadmin:rw

        ports:
            - "105:80"

        user: "${UID}:${GID}"

        restart: unless-stopped

        env_file:
            - "./.env"

        networks:
            - postgres-network

    redis:
      image: redis:latest
      env_file:
        - .env
      ports:
        - "6380:6379"
      volumes:
        - redisdata:/data
      networks:
        - postgres-network

networks:
    postgres-network:
      driver: bridge

volumes:
  pgdata:
  pgadmin:
  redisdata:

